version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=transacoes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  api:
    build:
      context: api
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api/:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
